

server:
  port: 8088
spring:
  application:
    name: order-service
#  data:
#    cassandra:
#      contact-points: localhost
#      port: 9042
#      keyspace-name: order_keyspace
#      local-datacenter: datacenter1
#      schema-action: create-if-not-exists

#  cassandra:
#    contact-points: localhost
#    port: 9042
#    keyspace-name: order_keyspace
#    local-datacenter: datacenter1
#    schema-action: none
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      local-datacenter: datacenter1
      schema-action: none
      keyspace-name: order_keyspace

# Cassandra Migration cấu hình
cassandra:
  migration:
    keyspace-name: order_keyspace
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    base-package: com.example.order_service




  kafka:
    #CONFIGGG
    bootstrap-servers: 10.0.110.5:9092

    #    consumer:
    #      group-id: order-service
    #      auto-offset-reset: earliest
    #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #    producer:
    #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.order_service.event.produce

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      missing-topics-fatal: false





#cassandra:
#  migration:
#    keyspace-name: system
#    contact-points: localhost
#    port: 9042
#    script-locations: classpath:cassandra/migration
#    create-keyspace: true
#    strategy: FAIL_ON_DUPLICATES
#    consistency-level: QUORUM
#    baseline-version: 0
#    baseline-description: Base migration




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true





