

server:
  port: 8088
spring:
  application:
    name: order-service
#  data:
#    cassandra:
#      contact-points: localhost
#      port: 9042
#      keyspace-name: order_keyspace
#      local-datacenter: datacenter1
#      schema-action: create-if-not-exists

#  cassandra:
#    contact-points: localhost
#    port: 9042
#    keyspace-name: order_keyspace
#    local-datacenter: datacenter1
#    schema-action: none
  cassandra:
    contact-points:
      - 127.0.0.1
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: order_keyspace
    schema-action: none

  kafka:
    #CONFIGGG
    bootstrap-servers: 192.168.1.72:9092

    #    consumer:
    #      group-id: order-service
    #      auto-offset-reset: earliest
    #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #    producer:
    #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: com.example.product_service.event.StockConfirmedEvent:com.example.order_service.event.StockConfirmedEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      missing-topics-fatal: false
    admin:
      auto-create: true



# Cassandra Migration cấu hình
cassandra:
  migration:
    keyspace-name: order_keyspace
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    base-package: com.example.order_service

#cassandra:
#  migration:
#    keyspace-name: system
#    contact-points: localhost
#    port: 9042
#    script-locations: classpath:cassandra/migration
#    create-keyspace: true
#    strategy: FAIL_ON_DUPLICATES
#    consistency-level: QUORUM
#    baseline-version: 0
#    baseline-description: Base migration




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true





