server:
  port: 8085
spring:
  application:
    name: wallet-service
  data:
    mongodb:
      uri: mongodb://localhost:27018/wallet_db
  kafka:
    #CONFIGGG
    bootstrap-servers: 192.168.1.72:9092


    consumer:
      group-id: wallet-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.wallet_service.event.produce

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      missing-topics-fatal: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true