

server:
  port: 8089
spring:
  application:
    name: payment-service

  cassandra:
    contact-points:
      - 127.0.0.1
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: order_keyspace
    schema-action: none

  kafka:
    #CONFIGGG
    bootstrap-servers: 192.168.1.72:9092

    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: com.example.order_service.event.OrderCreatedEvent:com.example.payment_service.event.OrderCreatedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      missing-topics-fatal: false



# Cassandra Migration cấu hình
cassandra:
  migration:
    keyspace-name: order_keyspace
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    base-package: com.example.payment_service


logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: DEBUG



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true





